# Generated by Django 5.1 on 2024-09-19 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kdb', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='race',
            name='start_at',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterUniqueTogether(
            name='horse',
            unique_together={('horse_key',)},
        ),
    ]
