# Generated by Django 5.1 on 2024-09-19 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kdb', '0002_race_start_at_alter_horse_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='race',
            name='final_600m_time',
            field=models.FloatField(blank=True),
        ),
    ]
