# Generated by Django 5.1 on 2024-09-19 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kdb', '0003_alter_race_final_600m_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='race',
            name='final_600m_time',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
