# Generated by Django 5.1 on 2024-09-19 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kdb', '0004_alter_race_final_600m_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='race',
            name='weight',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='race',
            name='weight_change',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
