# Generated by Django 5.1 on 2024-09-21 10:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kdb', '0006_pedigree_alter_horse_horse_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='horse',
            name='birth_year',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='horse',
            name='coat_color',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='horse',
            name='father',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children_as_father', to='kdb.horse'),
        ),
        migrations.AddField(
            model_name='horse',
            name='mother',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children_as_mother', to='kdb.horse'),
        ),
        migrations.AddField(
            model_name='horse',
            name='sex',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
