# Generated by Django 5.1 on 2024-09-21 10:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kdb', '0007_horse_birth_year_horse_coat_color_horse_father_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Pedigree',
        ),
    ]
