# Generated by Django 5.1 on 2024-09-21 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kdb', '0009_horse_race_result_horse_race_text_horse_relatives'),
    ]

    operations = [
        migrations.AlterField(
            model_name='horse',
            name='birth_year',
            field=models.CharField(blank=True, max_length=12, null=True),
        ),
        migrations.AlterField(
            model_name='horse',
            name='horse_key',
            field=models.CharField(max_length=10),
        ),
    ]
