# Generated by Django 5.1 on 2024-09-21 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kdb', '0013_remove_horse_father_remove_horse_mother_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='horse',
            name='horse_key',
            field=models.CharField(max_length=10, unique=True),
        ),
    ]
