# Generated by Django 5.1 on 2024-09-22 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kdb', '0014_alter_horse_horse_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='horse',
            name='is_stallion',
            field=models.BooleanField(default=False),
        ),
    ]
