# Generated by Django 5.1 on 2024-09-23 06:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kdb', '0015_horse_is_stallion'),
    ]

    operations = [
        migrations.CreateModel(
            name='RaceResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('race_id', models.CharField(max_length=12)),
                ('horse_key', models.CharField(max_length=10)),
                ('horse_number', models.IntegerField()),
                ('running_time', models.CharField(max_length=255)),
                ('odds', models.FloatField()),
                ('passing_order', models.CharField(max_length=255)),
                ('finish_position', models.IntegerField()),
                ('weight', models.IntegerField(blank=True, null=True)),
                ('weight_change', models.IntegerField(blank=True, null=True)),
                ('handicap', models.FloatField()),
                ('final_600m_time', models.FloatField(blank=True, null=True)),
                ('popularity', models.IntegerField()),
                ('jockey', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kdb.jockey')),
            ],
            options={
                'unique_together': {('race_id', 'horse_number')},
            },
        ),
    ]
