# Generated by Django 5.1 on 2024-09-23 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kdb', '0016_raceresult'),
    ]

    operations = [
        migrations.AddField(
            model_name='horse',
            name='farm_key',
            field=models.CharField(blank=True, max_length=7, null=True),
        ),
        migrations.AddField(
            model_name='horse',
            name='farm_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='horse',
            name='owner_key',
            field=models.CharField(blank=True, max_length=8, null=True),
        ),
        migrations.AddField(
            model_name='horse',
            name='owner_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='horse',
            name='trainer_key',
            field=models.CharField(blank=True, max_length=7, null=True),
        ),
        migrations.AddField(
            model_name='horse',
            name='trainer_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='horse',
            name='is_stallion',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
