# Generated by Django 5.1 on 2024-09-23 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kdb', '0017_horse_farm_key_horse_farm_name_horse_owner_key_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='horse',
            name='prize',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
