# Generated by Django 5.1 on 2024-09-23 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kdb', '0018_horse_prize'),
    ]

    operations = [
        migrations.AddField(
            model_name='horse',
            name='training_center',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
    ]
