# Generated by Django 5.1.2 on 2024-10-24 07:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kdb', '0019_horse_training_center'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='race',
            options={'ordering': ['horse_number']},
        ),
    ]
